apiVersion: v1
kind: Service
metadata:
  name: lc-metadata
  namespace: kube-system
spec:
  selector:
    app: lc-metadata
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
