apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: local-cloud-metadata
  annotations:
    cert-manager.io/inject-ca-from: kube-system/lcm-webhook
webhooks:
- name: lc-metadata.kube-system.svc
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: lc-metadata
      namespace: kube-system
      path: /webhook/mutate
      port: 443
  rules:
  - operations: [ "CREATE", "UPDATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  sideEffects: NoneOnDryRun

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lcm-webook
  namespace: kube-system
spec:
  secretName: lcm-webhook
  dnsNames:
  - lc-metadata.kube-system.svc
  - lc-metadata.kube-system.svc.cluster.local
  issuerRef:
    name: letsencrypt
