apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: main
          image: alpine
          command:
            - sleep
            - infinity
          resources:
            requests:
              memory: 64Mi
              cpu: 10m
